server:
    port:   9000
    
spring:
  application:
    name: project-gateway

management:
  endpoint:
    routes:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
    routes:
        userservice:    /user/**
