server:
  port:   9500
    
spring:
  application:
    name:   userservice
    
spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:    jdbc:mysql://localhost:3306/videoanalytics
    username:   myuser
    password:   mypassword
  jpa:
    hibernate:
      ddl-auto:   update
      dialect:    org.hibernate.dialect.MySQLDialect