server:
  port:   9500
    
spring:
  application:
    name:   userservice
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:    jdbc:mysql://localhost:3306/videoanalytics
    username:   myuser
    password:   mypassword
  jpa:
    hibernate:
      ddl-auto: none
      dialect:    org.hibernate.dialect.MySQLDialect
  
