server:
  port:   9500
    
spring:
  application:
    name:   userservice
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:    jdbc:mysql://localhost:3306/videoanalytics
    username:   myuser
    password:   mypassword
  jpa:
    hibernate:
      ddl-auto: none
      dialect:    org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
        application-database:   userDP
        username:   app_user
        password:   app_password
        database:   userDP
        port:   27017
        host:   localhost
  
logging:
  level:
    org:
      springframework:
        web:  DEBUG
      hibernate:  ERROR
